# Numpy

NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

### Why Use NumPy?

In Python we have lists that serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

Arrays are very frequently used in data science, where speed and resources are very important.

### Why is NumPy Faster Than Lists?

NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

This behavior is called locality of reference in computer science.

This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

### Which Language is NumPy written in?

NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++.

### Create a NumPy ndarray Object

NumPy is used to work with arrays. The array object in NumPy is called ndarray.

We can create a NumPy ndarray object by using the array() function.

In [11]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr)) 

# ndarray = N-dimensional array

[1 2 3 4 5]
<class 'numpy.ndarray'>


To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:

In [12]:
import numpy as np

arr = np.array((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]


## Dimensions in Arrays

A dimension in arrays is one level of array depth (nested arrays).

nested array: are arrays that have arrays as their elements.

### 0-D Arrays

0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.


In [13]:
import numpy as np

arr = np.array(42)

print(arr) 

print("Array is of type: ", type(arr)) 
  
# Printing array dimensions (axes) 
print("No. of dimensions: ", arr.ndim) 
  
# Printing shape of array 
print("Shape of array: ", arr.shape) 
  
# Printing size (total number of elements) of array 
print("Size of array: ", arr.size) 
  
# Printing type of elements in array 
print("Array stores elements of type: ", arr.dtype) 

42
Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  0
Shape of array:  ()
Size of array:  1
Array stores elements of type:  int32


### 1-D Arrays

An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

These are the most common and basic arrays.

In [14]:
arr1 = np.array([1, 2, 3, 4, 5])

print(arr1) 
  
# Printing array dimensions (axes) 
print("No. of dimensions: ", arr1.ndim) 
  
# Printing shape of array 
print("Shape of array: ", arr1.shape) 
  
# Printing size (total number of elements) of array 
print("Size of array: ", arr1.size) 
  
# Printing type of elements in array 
print("Array stores elements of type: ", arr1.dtype) 

[1 2 3 4 5]
No. of dimensions:  1
Shape of array:  (5,)
Size of array:  5
Array stores elements of type:  int32


### 2-D Arrays

An array that has 1-D arrays as its elements is called a 2-D array.

These are often used to represent matrix or 2nd order tensors.

**Note: NumPy has a whole sub module dedicated towards matrix operations called numpy.mat**

In [15]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

print(arr2) 
  
# Printing array dimensions (axes) 
print("No. of dimensions: ", arr2.ndim) 
  
# Printing shape of array 
print("Shape of array: ", arr2.shape) 
  
# Printing size (total number of elements) of array 
print("Size of array: ", arr2.size) 
  
# Printing type of elements in array 
print("Array stores elements of type: ", arr2.dtype) 

[[1 2 3]
 [4 5 6]]
No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6
Array stores elements of type:  int32


### 3-D arrays

An array that has 2-D arrays (matrices) as its elements is called 3-D array.

These are often used to represent a 3rd order tensor.

In [16]:
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr3) 
  
# Printing array dimensions (axes) 
print("No. of dimensions: ", arr3.ndim) 
  
# Printing shape of array 
print("Shape of array: ", arr3.shape) 
  
# Printing size (total number of elements) of array 
print("Size of array: ", arr3.size) 
  
# Printing type of elements in array 
print("Array stores elements of type: ", arr3.dtype) 

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
No. of dimensions:  3
Shape of array:  (2, 2, 3)
Size of array:  12
Array stores elements of type:  int32


## Higher Dimensional Arrays

An array can have any number of dimensions.

When the array is created, you can define the number of dimensions by using the ndmin argument.

In [17]:
a = np.array([1, 2, 3, 4], ndmin=5)

print(a)
print('number of dimensions :', a.ndim) 

[[[[[1 2 3 4]]]]]
number of dimensions : 5
